version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_USER
        - MYSQL_ROOT_PASSWORD
    container_name: mariadb
    restart: always
    networks:
      - docker-network
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - docker-network
    env_file:
      - .env
    init : true
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    ports:
     - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - docker-network

volumes:
  wordpress:
    driver_opts:
      type: bind
      device: /home/aessabir/data/wordpress
      o : bind
  mariadb:
    driver_opts:
      type: bind
      device: /home/aessabir/data/database
      o : bind

networks:
  docker-network:
    driver: bridge